# Generated by Django 6.0.8 on 2026-08-17 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='theatres.theatre'),
        ),
    ]
