# Generated by Django 6.0.8 on 2026-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_code',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
