# Generated by Django 6.0.8 on 2026-08-20 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
